// ============================================================
// 엔트리(Entry) 공통 블록 카탈로그 — 시작/흐름/판단/계산/자료/생김새/인공지능
// 캡션은 실제 엔트리 화면 표기를 따른다. (▼ = 드롭다운)
// code.entryPy : 엔트리 파이썬(텍스트 코딩 모드) 문법
// code.py      : 일반 파이썬(roboid/CodingRider 등 독립 실행) 문법
// ============================================================

export const ENTRY_COLORS = {
  start:    { fill: '#00b400', dark: '#009400', label: '시작' },
  flow:     { fill: '#19baea', dark: '#1498c0', label: '흐름' },
  moving:   { fill: '#ad3efb', dark: '#8b19db', label: '움직임' },
  looks:    { fill: '#ff3a61', dark: '#c72042', label: '생김새' },
  sound:    { fill: '#67b100', dark: '#508a00', label: '소리' },
  judge:    { fill: '#4562f5', dark: '#1b3ad8', label: '판단' },
  calc:     { fill: '#f4af18', dark: '#ff7f00', label: '계산' },
  variable: { fill: '#dd47d8', dark: '#b819b3', label: '자료' },
  func:     { fill: '#de5c04', dark: '#a14100', label: '함수' },
  ai:       { fill: '#8222ff', dark: '#670bdd', label: '인공지능' },
  hardware: { fill: '#00b6b1', dark: '#008380', label: '하드웨어' },
  expansion:{ fill: '#ef6d6d', dark: '#c63f3f', label: '확장' },
};

const OPS = [['=', 'EQUAL', '=='], ['>', 'GREATER', '>'], ['<', 'LESS', '<'], ['≥', 'GREATER_OR_EQUAL', '>='], ['≤', 'LESS_OR_EQUAL', '<='], ['≠', 'NOT_EQUAL', '!=']];
const KEYS = [['q','q'],['w','w'],['e','e'],['r','r'],['a','a'],['s','s'],['d','d'],['스페이스','space'],['위쪽 화살표','up'],['아래쪽 화살표','down'],['왼쪽 화살표','left'],['오른쪽 화살표','right'],['엔터','enter'],['1','1'],['2','2'],['3','3']];

// 파이썬 들여쓰기 유틸: 컴파일러가 ${BODY}/${ELSE}를 채울 때 사용
export const ENTRY_COMMON_BLOCKS = [
  // ---------------- 시작 ----------------
  { id: 'when_run_button_click', cat: 'start', shape: 'hat', tpl: '시작하기 버튼을 클릭했을 때', params: {},
    code: { entryPy: 'def when_start():\n${BODY}', py: '# 시작하기 버튼을 클릭했을 때\n${BODY_FLAT}' } },
  { id: 'when_some_key_pressed', cat: 'start', shape: 'hat', tpl: '%KEY 키를 눌렀을 때',
    params: { KEY: { kind: 'dropdown', options: KEYS, def: 'q' } },
    code: { entryPy: 'def when_press_key(${KEY:q}):\n${BODY}', py: '# ${KEY:label} 키를 눌렀을 때 (키 입력 처리는 실행 환경에 따라 구현)\n${BODY_FLAT}' } },
  { id: 'when_object_click', cat: 'start', shape: 'hat', tpl: '오브젝트를 클릭했을 때', params: {},
    code: { entryPy: 'def when_click_object_on():\n${BODY}', py: '# 오브젝트를 클릭했을 때\n${BODY_FLAT}' } },
  { id: 'when_message_cast', cat: 'start', shape: 'hat', tpl: '%MSG 신호를 받았을 때',
    params: { MSG: { kind: 'text', def: '신호' } },
    code: { entryPy: 'def when_get_signal(${MSG:q}):\n${BODY}', py: '# "${MSG}" 신호를 받았을 때\n${BODY_FLAT}' } },

  // ---------------- 흐름 ----------------
  { id: 'wait_second', cat: 'flow', shape: 'stack', tpl: '%SEC 초 기다리기',
    params: { SEC: { kind: 'value', def: 2 } },
    code: { entryPy: 'Entry.wait_for_sec(${SEC})', py: 'wait(${SEC} * 1000)' } },
  { id: 'repeat_basic', cat: 'flow', shape: 'c', tpl: '%N 번 반복하기',
    params: { N: { kind: 'value', def: 10 } },
    code: { entryPy: 'for i in range(${N}):\n${BODY}', py: 'for i in range(${N}):\n${BODY}' } },
  { id: 'repeat_inf', cat: 'flow', shape: 'c', tpl: '계속 반복하기', params: {},
    code: { entryPy: 'while True:\n${BODY}', py: 'while True:\n${BODY}' } },
  { id: 'repeat_while_true', cat: 'flow', shape: 'c', tpl: '%COND %MODE 반복하기',
    params: { COND: { kind: 'boolean' }, MODE: { kind: 'dropdown', options: [['이(가) 될 때까지', 'until'], ['인 동안', 'while']], def: 'until' } },
    code: { entryPy: (p) => (p.MODE === 'until' ? `while not (${p.COND}):\n\${BODY}` : `while ${p.COND}:\n\${BODY}`),
            py: (p) => (p.MODE === 'until' ? `while not (${p.COND}):\n\${BODY}` : `while ${p.COND}:\n\${BODY}`) } },
  { id: 'stop_repeat', cat: 'flow', shape: 'stack', tpl: '반복 중단하기', params: {},
    code: { entryPy: 'break', py: 'break' } },
  { id: '_if', cat: 'flow', shape: 'c', tpl: '만일 %COND (이)라면',
    params: { COND: { kind: 'boolean' } },
    code: { entryPy: 'if ${COND}:\n${BODY}', py: 'if ${COND}:\n${BODY}' } },
  { id: 'if_else', cat: 'flow', shape: 'c_else', tpl: '만일 %COND (이)라면', tplElse: '아니면',
    params: { COND: { kind: 'boolean' } },
    code: { entryPy: 'if ${COND}:\n${BODY}\nelse:\n${ELSE}', py: 'if ${COND}:\n${BODY}\nelse:\n${ELSE}' } },
  { id: 'wait_until_true', cat: 'flow', shape: 'stack', tpl: '%COND 이(가) 될 때까지 기다리기',
    params: { COND: { kind: 'boolean' } },
    code: { entryPy: 'while not (${COND}):\n    Entry.wait_for_sec(0.05)', py: 'wait_until(lambda: ${COND})' } },
  { id: 'stop_object', cat: 'flow', shape: 'stack', tpl: '%TARGET 코드 멈추기',
    params: { TARGET: { kind: 'dropdown', options: [['모든', 'all'], ['이', 'thisOnly'], ['자신의', 'thisObject'], ['이 오브젝트의 다른', 'thisThing']], def: 'all' } },
    code: { entryPy: 'Entry.stop_code("${TARGET}")', py: 'raise SystemExit  # 코드 멈추기' } },

  // ---------------- 판단 ----------------
  { id: 'boolean_basic_operator', cat: 'judge', shape: 'boolean', tpl: '%A %OP %B',
    params: { A: { kind: 'value', def: 10 }, OP: { kind: 'dropdown', options: OPS, def: 'EQUAL' }, B: { kind: 'value', def: 10 } },
    code: { entryPy: '(${A} ${OP:code} ${B})', py: '(${A} ${OP:code} ${B})' } },
  { id: 'boolean_and_or', cat: 'judge', shape: 'boolean', tpl: '%A %OP %B',
    params: { A: { kind: 'boolean' }, OP: { kind: 'dropdown', options: [['그리고', 'AND', 'and'], ['또는', 'OR', 'or']], def: 'AND' }, B: { kind: 'boolean' } },
    code: { entryPy: '(${A} ${OP:code} ${B})', py: '(${A} ${OP:code} ${B})' } },
  { id: 'boolean_not', cat: 'judge', shape: 'boolean', tpl: '%A (이)가 아니다',
    params: { A: { kind: 'boolean' } },
    code: { entryPy: '(not ${A})', py: '(not ${A})' } },
  { id: 'is_press_some_key', cat: 'judge', shape: 'boolean', tpl: '%KEY 키가 눌러져 있는가?',
    params: { KEY: { kind: 'dropdown', options: KEYS, def: 'q' } },
    code: { entryPy: 'Entry.is_key_pressed(${KEY:q})', py: 'key_pressed(${KEY:q})  # 키 입력은 실행 환경(keyboard 모듈 등)으로 구현' } },
  { id: 'True', cat: 'judge', shape: 'boolean', tpl: '참', params: {}, code: { entryPy: 'True', py: 'True' } },

  // ---------------- 계산 ----------------
  { id: 'calc_basic', cat: 'calc', shape: 'value', tpl: '%A %OP %B',
    params: { A: { kind: 'value', def: 10 }, OP: { kind: 'dropdown', options: [['+', 'PLUS', '+'], ['-', 'MINUS', '-'], ['x', 'MULTI', '*'], ['/', 'DIVIDE', '/']], def: 'PLUS' }, B: { kind: 'value', def: 10 } },
    code: { entryPy: '(${A} ${OP:code} ${B})', py: '(${A} ${OP:code} ${B})' } },
  { id: 'calc_rand', cat: 'calc', shape: 'value', tpl: '%A 부터 %B 사이의 무작위 수',
    params: { A: { kind: 'value', def: 0 }, B: { kind: 'value', def: 10 } },
    code: { entryPy: 'Entry.random(${A}, ${B})', py: 'random.randint(${A}, ${B})' } },
  { id: 'quotient_and_mod', cat: 'calc', shape: 'value', tpl: '%A / %B 의 %OP',
    params: { A: { kind: 'value', def: 10 }, OP: { kind: 'dropdown', options: [['몫', 'QUOTIENT', '//'], ['나머지', 'MOD', '%']], def: 'MOD' }, B: { kind: 'value', def: 3 } },
    code: { entryPy: '(${A} ${OP:code} ${B})', py: '(${A} ${OP:code} ${B})' } },
  { id: 'get_project_timer_value', cat: 'calc', shape: 'value', tpl: '초시계 값', params: {},
    code: { entryPy: 'Entry.timer()', py: '(time.time() - start_time)' } },
  { id: 'choose_project_timer_action', cat: 'calc', shape: 'stack', tpl: '초시계 %ACT',
    params: { ACT: { kind: 'dropdown', options: [['시작하기', 'START'], ['정지하기', 'STOP'], ['초기화하기', 'RESET']], def: 'START' } },
    code: { entryPy: 'Entry.timer_action("${ACT}")', py: 'start_time = time.time()  # 초시계 ${ACT:label}' } },

  // ---------------- 자료 ----------------
  { id: 'set_variable', cat: 'variable', shape: 'stack', tpl: '%VAR 를 %VALUE (으)로 정하기',
    params: { VAR: { kind: 'variable', def: '변수' }, VALUE: { kind: 'value', def: 10 } },
    code: { entryPy: '${VAR} = ${VALUE}', py: '${VAR} = ${VALUE}' } },
  { id: 'change_variable', cat: 'variable', shape: 'stack', tpl: '%VAR 에 %VALUE 만큼 더하기',
    params: { VAR: { kind: 'variable', def: '변수' }, VALUE: { kind: 'value', def: 10 } },
    code: { entryPy: '${VAR} += ${VALUE}', py: '${VAR} += ${VALUE}' } },
  { id: 'get_variable', cat: 'variable', shape: 'value', tpl: '%VAR 값',
    params: { VAR: { kind: 'variable', def: '변수' } },
    code: { entryPy: '${VAR}', py: '${VAR}' } },
  { id: 'show_variable', cat: 'variable', shape: 'stack', tpl: '변수 %VAR 보이기',
    params: { VAR: { kind: 'variable', def: '변수' } },
    code: { entryPy: 'Entry.show_variable("${VAR}")', py: 'print("${VAR} =", ${VAR})' } },
  { id: 'ask_and_wait', cat: 'variable', shape: 'stack', tpl: '%TEXT 을(를) 묻고 대답 기다리기',
    params: { TEXT: { kind: 'text', def: '안녕!' } },
    code: { entryPy: 'Entry.input(${TEXT:q})', py: 'answer = input(${TEXT:q})' } },
  { id: 'get_canvas_input_value', cat: 'variable', shape: 'value', tpl: '대답', params: {},
    code: { entryPy: 'Entry.answer()', py: 'answer' } },

  // ---------------- 생김새 ----------------
  { id: 'dialog_time', cat: 'looks', shape: 'stack', tpl: '%TEXT 을(를) %SEC 초 동안 %MODE',
    params: { TEXT: { kind: 'text', def: '안녕!' }, SEC: { kind: 'value', def: 4 }, MODE: { kind: 'dropdown', options: [['말하기', 'speak'], ['생각하기', 'think']], def: 'speak' } },
    code: { entryPy: 'Entry.print_for_sec(${TEXT:q}, ${SEC})', py: 'print(${TEXT:q}); wait(${SEC} * 1000)' } },
  { id: 'dialog', cat: 'looks', shape: 'stack', tpl: '%TEXT 을(를) %MODE',
    params: { TEXT: { kind: 'text', def: '안녕!' }, MODE: { kind: 'dropdown', options: [['말하기', 'speak'], ['생각하기', 'think']], def: 'speak' } },
    code: { entryPy: 'Entry.print(${TEXT:q})', py: 'print(${TEXT:q})' } },
  { id: 'change_to_next_shape', cat: 'looks', shape: 'stack', tpl: '%DIR 모양으로 바꾸기',
    params: { DIR: { kind: 'dropdown', options: [['다음', 'next'], ['이전', 'prev']], def: 'next' } },
    code: { entryPy: 'Entry.change_shape_next()', py: '# 오브젝트 모양 바꾸기(엔트리 화면 기능)' } },
  { id: 'show', cat: 'looks', shape: 'stack', tpl: '모양 보이기', params: {}, code: { entryPy: 'Entry.show()', py: '# 모양 보이기(엔트리 화면 기능)' } },
  { id: 'hide', cat: 'looks', shape: 'stack', tpl: '모양 숨기기', params: {}, code: { entryPy: 'Entry.hide()', py: '# 모양 숨기기(엔트리 화면 기능)' } },

  // ---------------- 소리 ----------------
  { id: 'sound_something_with_block', cat: 'sound', shape: 'stack', tpl: '소리 %SOUND 재생하기',
    params: { SOUND: { kind: 'text', def: '강아지 짖는소리' } },
    code: { entryPy: 'Entry.play_sound(${SOUND:q})', py: '# 소리 재생: ${SOUND} (엔트리 오브젝트 소리)' } },
  { id: 'sound_something_wait_with_block', cat: 'sound', shape: 'stack', tpl: '소리 %SOUND 재생하고 기다리기',
    params: { SOUND: { kind: 'text', def: '강아지 짖는소리' } },
    code: { entryPy: 'Entry.play_sound_and_wait(${SOUND:q})', py: '# 소리 재생하고 기다리기: ${SOUND}' } },

  // ---------------- 인공지능 (엔트리 AI 블록) ----------------
  // ※ 엔트리 인공지능 블록은 엔트리 파이썬(텍스트 모드)에서 지원되지 않아 블록 모드에서만 사용 가능.
  { id: 'ai_video_toggle', cat: 'ai', shape: 'stack', tpl: '비디오 화면 %MODE',
    params: { MODE: { kind: 'dropdown', options: [['보이기', 'on'], ['숨기기', 'off']], def: 'on' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 비디오 화면 ${MODE:label} — 엔트리 파이썬 미지원(블록 모드 전용)', py: '# [AI] 비디오 화면 ${MODE:label} — PC 카메라 사용(엔트리 AI 블록)' } },
  { id: 'ai_video_transparency', cat: 'ai', shape: 'stack', tpl: '비디오 투명도 효과를 %VAL 으로 정하기',
    params: { VAL: { kind: 'value', def: 0 } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 비디오 투명도 ${VAL}', py: '# [AI] 비디오 투명도 ${VAL}' } },
  { id: 'ai_recognition_toggle', cat: 'ai', shape: 'stack', tpl: '%MODEL 인식 %ACT',
    params: { MODEL: { kind: 'dropdown', options: [['사람', 'pose'], ['얼굴', 'face'], ['손', 'hand'], ['사물', 'object']], def: 'hand' }, ACT: { kind: 'dropdown', options: [['시작하기', 'on'], ['중지하기', 'off']], def: 'on' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] ${MODEL:label} 인식 ${ACT:label}', py: '# [AI] ${MODEL:label} 인식 ${ACT:label} (엔트리 비디오 감지)' } },
  { id: 'ai_recognition_show', cat: 'ai', shape: 'stack', tpl: '인식한 %MODEL %MODE',
    params: { MODEL: { kind: 'dropdown', options: [['사람', 'pose'], ['얼굴', 'face'], ['손', 'hand'], ['사물', 'object']], def: 'hand' }, MODE: { kind: 'dropdown', options: [['보이기', 'on'], ['숨기기', 'off']], def: 'on' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 인식한 ${MODEL:label} ${MODE:label}', py: '# [AI] 인식한 ${MODEL:label} ${MODE:label}' } },
  { id: 'ai_is_recognized', cat: 'ai', shape: 'boolean', tpl: '%MODEL 인식이 되었는가?',
    params: { MODEL: { kind: 'dropdown', options: [['사람', 'pose'], ['얼굴', 'face'], ['손', 'hand'], ['사물', 'object']], def: 'hand' } }, aiOnly: true,
    code: { entryPy: 'ai_recognized("${MODEL:label}")', py: 'ai_recognized("${MODEL:label}")  # [AI] 엔트리 인식 결과' } },
  { id: 'ai_recognized_count', cat: 'ai', shape: 'value', tpl: '인식한 %MODEL 의 수',
    params: { MODEL: { kind: 'dropdown', options: [['사람', 'pose'], ['얼굴', 'face'], ['손', 'hand'], ['사물', 'object']], def: 'face' } }, aiOnly: true,
    code: { entryPy: 'ai_count("${MODEL:label}")', py: 'ai_count("${MODEL:label}")' } },
  { id: 'ai_hand_side', cat: 'ai', shape: 'boolean', tpl: '%N 번째 손이 %SIDE 인가?',
    params: { N: { kind: 'dropdown', options: [['1', '1'], ['2', '2']], def: '1' }, SIDE: { kind: 'dropdown', options: [['오른손', 'right'], ['왼손', 'left']], def: 'right' } }, aiOnly: true,
    code: { entryPy: 'ai_hand_side(${N}, "${SIDE:label}")', py: 'ai_hand_side(${N}, "${SIDE:label}")  # [AI] 손 인식' } },
  { id: 'ai_hand_gesture', cat: 'ai', shape: 'boolean', tpl: '%N 번째 손의 모양이 %G 인가?',
    params: { N: { kind: 'dropdown', options: [['1', '1'], ['2', '2']], def: '1' }, G: { kind: 'dropdown', options: [['편 손', 'open'], ['주먹', 'fist'], ['엄지 위로', 'thumbs_up'], ['엄지 아래로', 'thumbs_down'], ['브이', 'victory'], ['가리킨 손', 'point'], ['사랑해', 'iloveyou']], def: 'open' } }, aiOnly: true,
    code: { entryPy: 'ai_hand_gesture(${N}, "${G:label}")', py: 'ai_hand_gesture(${N}, "${G:label}")  # [AI] 손 모양 인식' } },
  { id: 'ai_face_attr', cat: 'ai', shape: 'value', tpl: '%N 번째 얼굴의 %ATTR',
    params: { N: { kind: 'dropdown', options: [['1', '1'], ['2', '2']], def: '1' }, ATTR: { kind: 'dropdown', options: [['성별', 'gender'], ['나이', 'age'], ['감정', 'emotion']], def: 'emotion' } }, aiOnly: true,
    code: { entryPy: 'ai_face("${ATTR:label}", ${N})', py: 'ai_face("${ATTR:label}", ${N})  # [AI] 얼굴 인식' } },
  { id: 'ai_face_emotion_is', cat: 'ai', shape: 'boolean', tpl: '%N 번째 얼굴의 감정이 %E 인가?',
    params: { N: { kind: 'dropdown', options: [['1', '1'], ['2', '2']], def: '1' }, E: { kind: 'dropdown', options: [['행복', 'happy'], ['슬픔', 'sad'], ['화남', 'angry'], ['놀람', 'surprised'], ['무표정', 'neutral']], def: 'happy' } }, aiOnly: true,
    code: { entryPy: 'ai_face_emotion(${N}, "${E:label}")', py: 'ai_face_emotion(${N}, "${E:label}")  # [AI] 표정 인식' } },
  { id: 'ai_speech_recognize', cat: 'ai', shape: 'stack', tpl: '%LANG 음성 인식하기',
    params: { LANG: { kind: 'dropdown', options: [['한국어', 'ko'], ['영어', 'en']], def: 'ko' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] ${LANG:label} 음성 인식하기', py: 'speech_text = ai_listen("${LANG:label}")  # [AI] 음성 인식' } },
  { id: 'ai_speech_text', cat: 'ai', shape: 'value', tpl: '음성을 문자로 바꾼 값', params: {}, aiOnly: true,
    code: { entryPy: 'speech_text', py: 'speech_text' } },
  { id: 'ai_tts', cat: 'ai', shape: 'stack', tpl: '%TEXT 읽어주기',
    params: { TEXT: { kind: 'text', def: '안녕!' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 읽어주기: ${TEXT}', py: 'ai_speak(${TEXT:q})  # [AI] 읽어주기(TTS)' } },
  { id: 'ai_tts_wait', cat: 'ai', shape: 'stack', tpl: '%TEXT 읽어주고 기다리기',
    params: { TEXT: { kind: 'text', def: '안녕!' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 읽어주고 기다리기: ${TEXT}', py: 'ai_speak(${TEXT:q}, wait=True)  # [AI] TTS' } },
  { id: 'ai_model_classify_video', cat: 'ai', shape: 'stack', tpl: '비디오 화면을 학습한 모델로 분류 %ACT',
    params: { ACT: { kind: 'dropdown', options: [['시작하기', 'on'], ['중지하기', 'off']], def: 'on' } }, aiOnly: true,
    code: { entryPy: '# [AI 블록] 학습한 모델로 분류 ${ACT:label}', py: '# [AI] 이미지 모델 분류 ${ACT:label} (엔트리 모델 학습)' } },
  { id: 'ai_model_classify', cat: 'ai', shape: 'stack', tpl: '학습한 모델로 분류하기', params: {}, aiOnly: true,
    code: { entryPy: '# [AI 블록] 학습한 모델로 분류하기', py: 'result = ai_classify()  # [AI] 학습한 모델로 분류' } },
  { id: 'ai_model_result_is', cat: 'ai', shape: 'boolean', tpl: '분류 결과가 %CLS 인가?',
    params: { CLS: { kind: 'text', def: '클래스1' } }, aiOnly: true,
    code: { entryPy: '(classification_result == ${CLS:q})', py: '(result == ${CLS:q})' } },
  { id: 'ai_model_result', cat: 'ai', shape: 'value', tpl: '분류 결과', params: {}, aiOnly: true,
    code: { entryPy: 'classification_result', py: 'result' } },
  { id: 'ai_model_confidence', cat: 'ai', shape: 'value', tpl: '%CLS 에 대한 신뢰도',
    params: { CLS: { kind: 'text', def: '클래스1' } }, aiOnly: true,
    code: { entryPy: 'confidence(${CLS:q})', py: 'confidence(${CLS:q})' } },
];
